#!/usr/bin/env bash
set -euo pipefail

: "${PRODUCTIVE_PROXY_LISTEN_HOST:?Missing PRODUCTIVE_PROXY_LISTEN_HOST}"
: "${PRODUCTIVE_PROXY_LISTEN_PORT:?Missing PRODUCTIVE_PROXY_LISTEN_PORT}"
: "${PRODUCTIVE_PROXY_AUTH_ENABLED:?Missing PRODUCTIVE_PROXY_AUTH_ENABLED}"
: "${PRODUCTIVE_PROXY_STATE_PATH:?Missing PRODUCTIVE_PROXY_STATE_PATH}"
: "${PRODUCTIVE_PROXY_EVENT_LOG_PATH:?Missing PRODUCTIVE_PROXY_EVENT_LOG_PATH}"
: "${PRODUCTIVE_PROXY_REDDIT_IDLE_SECONDS:?Missing PRODUCTIVE_PROXY_REDDIT_IDLE_SECONDS}"
: "${PRODUCTIVE_PROXY_REDDIT_HOST_SUFFIXES:?Missing PRODUCTIVE_PROXY_REDDIT_HOST_SUFFIXES}"
: "${PRODUCTIVE_PROXY_YOUTUBE_HOST_SUFFIXES:?Missing PRODUCTIVE_PROXY_YOUTUBE_HOST_SUFFIXES}"
: "${PRODUCTIVE_PROXY_YOUTUBE_SHORTS_PATH_MARKERS:?Missing PRODUCTIVE_PROXY_YOUTUBE_SHORTS_PATH_MARKERS}"

if [[ "$PRODUCTIVE_PROXY_AUTH_ENABLED" != "true" && "$PRODUCTIVE_PROXY_AUTH_ENABLED" != "false" ]]; then
  echo "PRODUCTIVE_PROXY_AUTH_ENABLED must be 'true' or 'false'" >&2
  exit 1
fi

if [[ "$PRODUCTIVE_PROXY_AUTH_ENABLED" == "true" ]]; then
  : "${PRODUCTIVE_PROXY_AUTH_USERNAME:?Missing PRODUCTIVE_PROXY_AUTH_USERNAME}"
  : "${PRODUCTIVE_PROXY_AUTH_PASSWORD:?Missing PRODUCTIVE_PROXY_AUTH_PASSWORD}"

  if [[ "$PRODUCTIVE_PROXY_AUTH_USERNAME" == *:* || "$PRODUCTIVE_PROXY_AUTH_PASSWORD" == *:* ]]; then
    echo "PRODUCTIVE_PROXY_AUTH_USERNAME and PRODUCTIVE_PROXY_AUTH_PASSWORD must not contain ':'" >&2
    exit 1
  fi

  exec mitmdump \
    --listen-host "$PRODUCTIVE_PROXY_LISTEN_HOST" \
    --listen-port "$PRODUCTIVE_PROXY_LISTEN_PORT" \
    --proxyauth "$PRODUCTIVE_PROXY_AUTH_USERNAME:$PRODUCTIVE_PROXY_AUTH_PASSWORD" \
    -s mitmproxy/addons/productive_policies.py
fi

exec mitmdump \
  --listen-host "$PRODUCTIVE_PROXY_LISTEN_HOST" \
  --listen-port "$PRODUCTIVE_PROXY_LISTEN_PORT" \
  -s mitmproxy/addons/productive_policies.py
